
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROW EPSILON IDENTIFIER NEWLINE PIPE QUOTED_STRING START_KWgrammar : START_KW IDENTIFIER newlines rulelistrulelist : rule rulelistrulelist : rulerule : IDENTIFIER ARROW altlist newlines\n            | IDENTIFIER ARROW altlistaltlist : seq PIPE altlistaltlist : seqseq : symbol seqseq : symbol : IDENTIFIERsymbol : QUOTED_STRINGsymbol : EPSILONnewlines : NEWLINE\n               | NEWLINE newlines'
    
_lr_action_items = {'START_KW':([0,],[2,]),'$end':([1,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[0,-13,-1,-3,-14,-9,-2,-10,-5,-7,-9,-11,-12,-4,-9,-8,-6,]),'IDENTIFIER':([2,4,5,8,9,10,12,13,14,15,16,17,18,19,20,21,],[3,6,-13,6,-14,12,-10,-5,-7,12,-11,-12,-4,12,-8,-6,]),'NEWLINE':([3,5,10,12,13,14,15,16,17,19,20,21,],[5,5,-9,-10,5,-7,-9,-11,-12,-9,-8,-6,]),'ARROW':([6,],[10,]),'PIPE':([10,12,14,15,16,17,19,20,],[-9,-10,19,-9,-11,-12,-9,-8,]),'QUOTED_STRING':([10,12,15,16,17,19,],[16,-10,16,-11,-12,16,]),'EPSILON':([10,12,15,16,17,19,],[17,-10,17,-11,-12,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'grammar':([0,],[1,]),'newlines':([3,5,13,],[4,9,18,]),'rulelist':([4,8,],[7,11,]),'rule':([4,8,],[8,8,]),'altlist':([10,19,],[13,21,]),'seq':([10,15,19,],[14,20,14,]),'symbol':([10,15,19,],[15,15,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> grammar","S'",1,None,None,None),
  ('grammar -> START_KW IDENTIFIER newlines rulelist','grammar',4,'p_grammar','gp_parser.py',12),
  ('rulelist -> rule rulelist','rulelist',2,'p_rulelist_multiple','gp_parser.py',20),
  ('rulelist -> rule','rulelist',1,'p_rulelist_single','gp_parser.py',25),
  ('rule -> IDENTIFIER ARROW altlist newlines','rule',4,'p_rule','gp_parser.py',30),
  ('rule -> IDENTIFIER ARROW altlist','rule',3,'p_rule','gp_parser.py',31),
  ('altlist -> seq PIPE altlist','altlist',3,'p_altlist_multiple','gp_parser.py',40),
  ('altlist -> seq','altlist',1,'p_altlist_single','gp_parser.py',45),
  ('seq -> symbol seq','seq',2,'p_seq_symbol','gp_parser.py',50),
  ('seq -> <empty>','seq',0,'p_seq_empty','gp_parser.py',55),
  ('symbol -> IDENTIFIER','symbol',1,'p_symbol_identifier','gp_parser.py',60),
  ('symbol -> QUOTED_STRING','symbol',1,'p_symbol_quoted','gp_parser.py',65),
  ('symbol -> EPSILON','symbol',1,'p_symbol_epsilon','gp_parser.py',70),
  ('newlines -> NEWLINE','newlines',1,'p_newlines','gp_parser.py',75),
  ('newlines -> NEWLINE newlines','newlines',2,'p_newlines','gp_parser.py',76),
]
